# --- Created by Slick DDL
# To stop Slick DDL generation, remove this comment and start using Evolutions

# --- !Ups

create table "authenticator" ("id" varchar(2000) NOT NULL,"user_id" VARCHAR(254) NOT NULL,"expiration_date" TIMESTAMP NOT NULL,"last_used" TIMESTAMP NOT NULL,"creation_date" TIMESTAMP NOT NULL);
create index "auth_idx" on "authenticator" ("id");
create table "mail_token" ("uuid" VARCHAR(254) NOT NULL PRIMARY KEY,"email" VARCHAR(254) NOT NULL,"creation_time" TIMESTAMP NOT NULL,"expiration_time" TIMESTAMP NOT NULL,"is_sign_up" BOOLEAN NOT NULL);
create table "oauth1" ("id" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL PRIMARY KEY,"token" VARCHAR(254) NOT NULL,"secret" VARCHAR(254) NOT NULL);
create table "oauth2" ("id" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL PRIMARY KEY,"access_token" VARCHAR(254) NOT NULL,"token_type" VARCHAR(254),"expires_in" INTEGER,"refresh_token" VARCHAR(254));
create table "password" ("id" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL PRIMARY KEY,"hasher" VARCHAR(254) NOT NULL,"password" VARCHAR(254) NOT NULL,"salt" VARCHAR(254));
create table "profile" ("id" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL PRIMARY KEY,"provider_id" VARCHAR(254) NOT NULL,"user_id" VARCHAR(254) NOT NULL,"first_name" VARCHAR(254),"last_name" VARCHAR(254),"full_name" VARCHAR(254),"email" VARCHAR(254),"avatar_url" VARCHAR(254),"auth_method" VARCHAR(254) NOT NULL,"oauth1_id" BIGINT,"oauth2_id" BIGINT,"password_id" BIGINT);
create index "profile_idx" on "profile" ("provider_id","user_id");
create table "user" ("id" VARCHAR(254) NOT NULL PRIMARY KEY,"main_id" BIGINT NOT NULL);

# --- !Downs

drop table "user";
drop table "profile";
drop table "password";
drop table "oauth2";
drop table "oauth1";
drop table "mail_token";
drop table "authenticator";

